FROM node:22.14.0 AS build
ARG VERSION
WORKDIR /src

COPY package*.json ./
COPY frontend/package*.json ./frontend/
RUN npm ci --workspace=frontend --ignore-scripts

WORKDIR /src/frontend
COPY ./frontend .
RUN VITE_VERSION="$VERSION" npm run build


FROM caddy:2.10.0
RUN apk add --no-cache caddy

WORKDIR /srv

COPY frontend/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /src/frontend/dist /srv

ENTRYPOINT ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
